# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: CI - Linux via ROS

# This determines when this workflow is run
on:
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.pre-commit-config.yaml'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.pre-commit-config.yaml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ros:
    name: ROS ${{ matrix.ROS_DISTRO }} - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # ROS2 Humble Hawksbill (May 2022 - May 2027)
          - ROS_DISTRO: humble
            os: Ubuntu 22.04 (Jammy)

          # ROS2 Jazzy Jalisco (May 2024 - May 2029)
          - ROS_DISTRO: jazzy
            os: Ubuntu 24.04 (Noble)

          # ROS2 Kilted Kayu (May 2025 - December 2026)
          - ROS_DISTRO: kilted
            os: Ubuntu 24.04 (Noble)

          # ROS2 Rolling Ridley
          - ROS_DISTRO: rolling
            os: Ubuntu 24.04 (Noble)
    env:
      PRERELEASE: true
      VERBOSE_OUTPUT: true
      VERBOSE_TESTS: true
      ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
      CCACHE_DIR: ${{ github.workspace }}/.ccache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.ROS_DISTRO }}-${{github.run_id}}
          restore-keys: ccache-${{ matrix.ROS_DISTRO }}-
      - uses: 'ros-industrial/industrial_ci@ba2a3d0f830f8051b356711a8df2fedfc5d256cf'

  check:
    if: always()
    name: check-ros-ci

    needs:
    - ros

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
